### ISSUE TITLE
 ‘class EPD215’ has no member named ‘placeStringAt’

### ISSUE THREAD

**Issue by nicocesar** [jarek319/EPD215#1]
From the example: 

```
EpaperQuoteDisplay.ino: In function ‘void loop()’:
EpaperQuoteDisplay.ino:33:10: error: ‘class EPD215’ has no member named ‘placeStringAt’
EpaperQuoteDisplay.ino:34:10: error: ‘class EPD215’ has no member named ‘placeStringAt’
```

Where is  ‘placeStringAt’ defined?

**Comment by jareklupinski** [comment]
It seems the example file was not updated with the latest version of the library. My apologies, I have just refreshed the example sketches in the github and they should work now.

I placed the placeStringAt function inside the example sketch, as the Adafruit GFX library has its own style of placing strings and I did not wish for them to conflict.

**Comment by nicocesar** [comment]
Updated the example thanks now I have issue #2
