### ISSUE TITLE
‘class SPIClass’ has no member named ‘beginTransaction’

### ISSUE THREAD

**Issue by nicocesar** [jarek319/EPD215#2]
/home/nico/sketchbook/libraries/EPD215/EPD215.cpp: In member function ‘void EPD215::initScreen()’:
/home/nico/sketchbook/libraries/EPD215/EPD215.cpp:269:9: error: ‘class SPIClass’ has no member named ‘beginTransaction’
     SPI.beginTransaction( SPISettings( 1000000, MSBFIRST, SPI_MODE0 ));
         ^
/home/nico/sketchbook/libraries/EPD215/EPD215.cpp:269:69: error: ‘SPISettings’ was not declared in this scope
     SPI.beginTransaction( SPISettings( 1000000, MSBFIRST, SPI_MODE0 ));
                                                                     ^

**Comment by jareklupinski** [comment]
Hmmm, which Device is selected in Tools -> Board?

I have developed this library with the Teensy-LC device in mind, and am making changes to make this library more universal.
