### ISSUE TITLE
Res# and Busy pins swapped between old board version and new version

### ISSUE THREAD

**Issue by michalsok** [jarek319/EPD215#4]
Hello.
I have just stumbled across the OSHPark shared design for ePaper interface and I have ordered the PCBs.
After assembling the interface I could not get this library example files to work.
After many experiments and probing I realized that the newer board with temperature sensor was designed and the two signals for RES# and BUSY (pins 14 and 15) are swapped between the two designs.
Since the older board is referenced in OSHPark and Hackaday, please note the different pin assignments in the example files like bellow:

// initialize epaper with pin numbers for cs, dc, rs, bs, d0, d1 for software SPI
//EPD215 epaper( 17, 16, 15, 14, 13, 11 );
// initialize epaper with pin numbers for cs, dc, rs, bs for hardware SPI
//EPD215 epaper( 17, 16, 15, 14 );
// **for original interface board design** (minus temp sensor) use these settings (pins 14 and 15 swapped):
// initialize epaper with pin numbers for cs, dc, rs, bs, d0, d1 for software SPI
//EPD215 epaper( 17, 16, 14, 15, 13, 11 );
// initialize epaper with pin numbers for cs, dc, rs, bs for hardware SPI
//EPD215 epaper( 17, 16, 14, 15 );

Thank you,
Michal Sokolowski

**Comment by pdp7** [comment]
Hi @michalsok, yes I happened to lay out the board to use those pins.  Unfortunately, this means [the following has to be changed](https://github.com/pdp7/kicad-teensy-epaper#source-code):
```
EPD215 epaper( 17, 16, 14, 15, 13, 11 );
```
I'm thinking about how to make my sample code in [kicad-teensy-epaper](https://github.com/pdp7/kicad-teensy-epaper) easier to use and hopefully will be updating it soon.

**Comment by jareklupinski** [comment]
will add this to the Readme, thank you :)
